### ISSUE TITLE
Fix CRAN issue: test for suggested pacakge need to be conditional on availability

### ISSUE THREAD

**Issue by christophM** [christophM/iml#145]
https://cran.r-project.org/web/checks/check_results_iml.html

See Also:
https://cran.r-project.org/doc/manuals/R-exts.html#Suggested-packages

**Comment by pat-s** [comment]
For tests, you can simply use `skip_on_os()`.

It is different for examples since these cannot be easily skipped. Also there are more opinions out there how to "correctly" condition examples and how to deal with suggested packages.

Note that the future note in the check results is already fixed (some months ago).

With respect to #146, I would only skip the tests on Solaris and not skip all h2o/keras tests completely on CRAN if that works out.
